name: firstjob
on: 
 push:
  branches: [main]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
       uses: action/checkout@v4
     - name: run build
       run: echo " Running build"
  test:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: action/checkout@v4
     - name: run build
       run: echo " Running test"      
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: action/checkout@v4
       - name: run build
         run: echo " Running depoy"   
