name: firstjob
on: 
 push:
  branches: [main]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
       uses: actions/checkout@v4
     - name: run build
       run: echo " Running build"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4
     - name: run build
       run: echo " Running test"      
  deploy:
     needs: [build,test]
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v4
       - name: run build
         run: echo " Running depoy"   
