name: work_with_matrix
on: [push]

jobs:
 build:
  runs-on: ${{matrix.os}}
  strategy:
     matrix:
       os: [ubuntu-latest,windows-latest,macos-latest]
      
  steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: building project
     run: echo "building projecti running on ${{matrix.os}}" > build.txt

   - name: build artifacts
     uses: actions/upload-artifact@v4
     with: 
        name: build-output1
        path: build.txt
 deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Download artifacts
       uses: actions/download-artifact@v4
       with:
        name: build-output1
        with: build.txt
        
     - name: deploy project
       run: cat build.txt
 
  
