name: test the protection of workflow
on:
   workflow_dispatch:

env:
 Day_of_week: Tuesday

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: F=Greeting Hello
      run: |
          echo "Say hello with me"
          echo "Gretting Today is ${{env.Days_of_week}}"
          echo "Event triggered by"
      env:
        First_name: Radha
    
